source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'CompatibleCocos2d_Example', :exclusive => true do
  pod "CompatibleCocos2d", :path => "../"
end

target 'CompatibleCocos2d_Tests', :exclusive => true do
  pod "CompatibleCocos2d", :path => "../"

  
end
